name: heron_law
channels:
  - conda-forge
dependencies:
  - conda-lock
  - ipykernel
  - jupyterlab
  - matplotlib
  - openpyxl
  - pandas
  - pip
  - plotly
  - pyarrow
  - quarto
  - seaborn
  - git-lfs
  - datasets
